name: Daily Job Fetch and Upload

on:
  schedule:
    - cron: '0 7 * * *'  # every day at 7:00 AM UTC
  workflow_dispatch:

jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jobspy google-auth google-api-python-client pandas

      - name: Prepare Google Credentials JSON
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > creds.json

      - name: Run job fetch script
        run: |
          python job_fetcher.py
        env:
          SERVICE_ACCOUNT_FILE: creds.json
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
